build: fix mingw build with -D_FORTIFY_SOURCE=2
The Windows specific header wave_out.h is redefining various
gnu compiler specific keywords. It was likely introduced when things
got ported to MSVC, but it didn't take mingw into account.

There are two problems, __attribute__() gets used in system headers and
removing it can change behaviour and "restrict" being removed can
lead to less optimized code. __inline seems to work fine though, but is not needed.

CFLAGS="-D_FORTIFY_SOURCE=2 -O2" exposed this now because a required
__attribute__() is missing:

In file included from speexdec.c:54:
C:/msys64/ucrt64/include/io.h: In function '_open':
C:/msys64/ucrt64/include/io.h:407:7: error: invalid use of '__builtin_va_arg_pack_len ()'
  407 |   if (__builtin_va_arg_pack_len() > 1)

Fix by only enabling those macros when building with MSVC.